//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 10:39:13 PM ECT
//

package ec.gob.sri.note.delivery.v110;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Detalle de una guia de remision. Contiene los elementos de cada fila de la guia.
 *
 * <p>Java class for detalle complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="detalle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codigoInterno" type="{}codigoInterno" minOccurs="0"/&gt;
 *         &lt;element name="codigoAdicional" type="{}codigoAdicional" minOccurs="0"/&gt;
 *         &lt;element name="descripcion" type="{}descripcion"/&gt;
 *         &lt;element name="cantidad" type="{}cantidad"/&gt;
 *         &lt;element name="detallesAdicionales" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="detAdicional" maxOccurs="3" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="nombre" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="300"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="valor" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;minLength value="1"/&gt;
 *                                 &lt;maxLength value="300"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "detalle",
    propOrder = {
      "codigoInterno",
      "codigoAdicional",
      "descripcion",
      "cantidad",
      "detallesAdicionales"
    })
public class Detalle {

  protected String codigoInterno;
  protected String codigoAdicional;

  @XmlElement(required = true)
  protected String descripcion;

  @XmlElement(required = true)
  protected BigDecimal cantidad;

  protected Detalle.DetallesAdicionales detallesAdicionales;

  /**
   * Gets the value of the codigoInterno property.
   *
   * @return possible object is {@link String }
   */
  public String getCodigoInterno() {
    return codigoInterno;
  }

  /**
   * Sets the value of the codigoInterno property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCodigoInterno(String value) {
    this.codigoInterno = value;
  }

  /**
   * Gets the value of the codigoAdicional property.
   *
   * @return possible object is {@link String }
   */
  public String getCodigoAdicional() {
    return codigoAdicional;
  }

  /**
   * Sets the value of the codigoAdicional property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCodigoAdicional(String value) {
    this.codigoAdicional = value;
  }

  /**
   * Gets the value of the descripcion property.
   *
   * @return possible object is {@link String }
   */
  public String getDescripcion() {
    return descripcion;
  }

  /**
   * Sets the value of the descripcion property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescripcion(String value) {
    this.descripcion = value;
  }

  /**
   * Gets the value of the cantidad property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getCantidad() {
    return cantidad;
  }

  /**
   * Sets the value of the cantidad property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setCantidad(BigDecimal value) {
    this.cantidad = value;
  }

  /**
   * Gets the value of the detallesAdicionales property.
   *
   * @return possible object is {@link Detalle.DetallesAdicionales }
   */
  public Detalle.DetallesAdicionales getDetallesAdicionales() {
    return detallesAdicionales;
  }

  /**
   * Sets the value of the detallesAdicionales property.
   *
   * @param value allowed object is {@link Detalle.DetallesAdicionales }
   */
  public void setDetallesAdicionales(Detalle.DetallesAdicionales value) {
    this.detallesAdicionales = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="detAdicional" maxOccurs="3" minOccurs="0"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;attribute name="nombre" use="required"&gt;
   *                   &lt;simpleType&gt;
   *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
   *                       &lt;minLength value="1"/&gt;
   *                       &lt;maxLength value="300"/&gt;
   *                     &lt;/restriction&gt;
   *                   &lt;/simpleType&gt;
   *                 &lt;/attribute&gt;
   *                 &lt;attribute name="valor" use="required"&gt;
   *                   &lt;simpleType&gt;
   *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
   *                       &lt;minLength value="1"/&gt;
   *                       &lt;maxLength value="300"/&gt;
   *                     &lt;/restriction&gt;
   *                   &lt;/simpleType&gt;
   *                 &lt;/attribute&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"detAdicional"})
  public static class DetallesAdicionales {

    protected List<Detalle.DetallesAdicionales.DetAdicional> detAdicional;

    /**
     * Gets the value of the detAdicional property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the detAdicional property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getDetAdicional().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * Detalle.DetallesAdicionales.DetAdicional }
     */
    public List<Detalle.DetallesAdicionales.DetAdicional> getDetAdicional() {
      if (detAdicional == null) {
        detAdicional = new ArrayList<Detalle.DetallesAdicionales.DetAdicional>();
      }
      return this.detAdicional;
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="nombre" use="required"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="1"/&gt;
     *             &lt;maxLength value="300"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="valor" use="required"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;minLength value="1"/&gt;
     *             &lt;maxLength value="300"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DetAdicional {

      @XmlAttribute(name = "nombre", required = true)
      protected String nombre;

      @XmlAttribute(name = "valor", required = true)
      protected String valor;

      /**
       * Gets the value of the nombre property.
       *
       * @return possible object is {@link String }
       */
      public String getNombre() {
        return nombre;
      }

      /**
       * Sets the value of the nombre property.
       *
       * @param value allowed object is {@link String }
       */
      public void setNombre(String value) {
        this.nombre = value;
      }

      /**
       * Gets the value of the valor property.
       *
       * @return possible object is {@link String }
       */
      public String getValor() {
        return valor;
      }

      /**
       * Sets the value of the valor property.
       *
       * @param value allowed object is {@link String }
       */
      public void setValor(String value) {
        this.valor = value;
      }
    }
  }
}
