//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 10:39:13 PM ECT
//

package ec.gob.sri.note.delivery.v110;

import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the ec.gob.sri.note.delivery.v110 package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: ec.gob.sri.note.delivery.v110
   */
  public ObjectFactory() {}

  /** Create an instance of {@link GuiaRemision } */
  public GuiaRemision createGuiaRemision() {
    return new GuiaRemision();
  }

  /** Create an instance of {@link Detalle } */
  public Detalle createDetalle() {
    return new Detalle();
  }

  /** Create an instance of {@link Detalle.DetallesAdicionales } */
  public Detalle.DetallesAdicionales createDetalleDetallesAdicionales() {
    return new Detalle.DetallesAdicionales();
  }

  /** Create an instance of {@link Destinatario } */
  public Destinatario createDestinatario() {
    return new Destinatario();
  }

  /** Create an instance of {@link GuiaRemision.InfoAdicional } */
  public GuiaRemision.InfoAdicional createGuiaRemisionInfoAdicional() {
    return new GuiaRemision.InfoAdicional();
  }

  /** Create an instance of {@link InfoTributaria } */
  public InfoTributaria createInfoTributaria() {
    return new InfoTributaria();
  }

  /** Create an instance of {@link GuiaRemision.InfoGuiaRemision } */
  public GuiaRemision.InfoGuiaRemision createGuiaRemisionInfoGuiaRemision() {
    return new GuiaRemision.InfoGuiaRemision();
  }

  /** Create an instance of {@link GuiaRemision.Destinatarios } */
  public GuiaRemision.Destinatarios createGuiaRemisionDestinatarios() {
    return new GuiaRemision.Destinatarios();
  }

  /** Create an instance of {@link MaquinaFiscal } */
  public MaquinaFiscal createMaquinaFiscal() {
    return new MaquinaFiscal();
  }

  /** Create an instance of {@link Detalle.DetallesAdicionales.DetAdicional } */
  public Detalle.DetallesAdicionales.DetAdicional createDetalleDetallesAdicionalesDetAdicional() {
    return new Detalle.DetallesAdicionales.DetAdicional();
  }

  /** Create an instance of {@link Destinatario.Detalles } */
  public Destinatario.Detalles createDestinatarioDetalles() {
    return new Destinatario.Detalles();
  }

  /** Create an instance of {@link GuiaRemision.InfoAdicional.CampoAdicional } */
  public GuiaRemision.InfoAdicional.CampoAdicional createGuiaRemisionInfoAdicionalCampoAdicional() {
    return new GuiaRemision.InfoAdicional.CampoAdicional();
  }
}
