//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.25 at 09:33:06 PM ECT 
//


package ec.gob.sri.note.debit.v100;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ec.gob.sri.note.debit.v110 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ec.gob.sri.note.debit.v110
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotaDebito }
     * 
     */
    public NotaDebito createNotaDebito() {
        return new NotaDebito();
    }

    /**
     * Create an instance of {@link NotaDebito.InfoAdicional }
     * 
     */
    public NotaDebito.InfoAdicional createNotaDebitoInfoAdicional() {
        return new NotaDebito.InfoAdicional();
    }

    /**
     * Create an instance of {@link NotaDebito.Motivos }
     * 
     */
    public NotaDebito.Motivos createNotaDebitoMotivos() {
        return new NotaDebito.Motivos();
    }

    /**
     * Create an instance of {@link NotaDebito.InfoNotaDebito }
     * 
     */
    public NotaDebito.InfoNotaDebito createNotaDebitoInfoNotaDebito() {
        return new NotaDebito.InfoNotaDebito();
    }

    /**
     * Create an instance of {@link InfoTributaria }
     * 
     */
    public InfoTributaria createInfoTributaria() {
        return new InfoTributaria();
    }

    /**
     * Create an instance of {@link MaquinaFiscal }
     * 
     */
    public MaquinaFiscal createMaquinaFiscal() {
        return new MaquinaFiscal();
    }

    /**
     * Create an instance of {@link Detalle }
     * 
     */
    public Detalle createDetalle() {
        return new Detalle();
    }

    /**
     * Create an instance of {@link Impuesto }
     * 
     */
    public Impuesto createImpuesto() {
        return new Impuesto();
    }

    /**
     * Create an instance of {@link Compensacion }
     * 
     */
    public Compensacion createCompensacion() {
        return new Compensacion();
    }

    /**
     * Create an instance of {@link Pago }
     * 
     */
    public Pago createPago() {
        return new Pago();
    }

    /**
     * Create an instance of {@link NotaDebito.InfoAdicional.CampoAdicional }
     * 
     */
    public NotaDebito.InfoAdicional.CampoAdicional createNotaDebitoInfoAdicionalCampoAdicional() {
        return new NotaDebito.InfoAdicional.CampoAdicional();
    }

    /**
     * Create an instance of {@link NotaDebito.Motivos.Motivo }
     * 
     */
    public NotaDebito.Motivos.Motivo createNotaDebitoMotivosMotivo() {
        return new NotaDebito.Motivos.Motivo();
    }

    /**
     * Create an instance of {@link NotaDebito.InfoNotaDebito.Impuestos }
     * 
     */
    public NotaDebito.InfoNotaDebito.Impuestos createNotaDebitoInfoNotaDebitoImpuestos() {
        return new NotaDebito.InfoNotaDebito.Impuestos();
    }

    /**
     * Create an instance of {@link NotaDebito.InfoNotaDebito.Compensaciones }
     * 
     */
    public NotaDebito.InfoNotaDebito.Compensaciones createNotaDebitoInfoNotaDebitoCompensaciones() {
        return new NotaDebito.InfoNotaDebito.Compensaciones();
    }

    /**
     * Create an instance of {@link NotaDebito.InfoNotaDebito.Pagos }
     * 
     */
    public NotaDebito.InfoNotaDebito.Pagos createNotaDebitoInfoNotaDebitoPagos() {
        return new NotaDebito.InfoNotaDebito.Pagos();
    }

}
