/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("io.freefair.lombok") version "8.4"
    id("com.diffplug.spotless") version "6.25.0"
}

spotless {
    java {
        // Choose a formatter, e.g., Google Java Format
        googleJavaFormat()

        // Optionally, add other steps
        formatAnnotations()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()

        // Specify target files (e.g., all .java files except those in build directory)
        target("src/**/*.java")
        targetExclude("build/**")
    }
}
version = "1.2.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("com.sun.xml.ws:jaxws-rt:4.0.1")
    implementation("net.sf.jasperreports:jasperreports:6.21.2")
    implementation("net.sf.barcode4j:barcode4j:2.1")
    implementation("org.apache.xmlgraphics:batik-all:1.18")
    implementation("com.github.librepdf:openpdf:1.3.30")
    compileOnly("org.projectlombok:lombok:1.18.30")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("roquiprinter.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.jar {
    // Customize the JAR file name
    archiveFileName.set("RoQuiPrinter-$version.jar")
}