/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("io.freefair.lombok") version "8.3"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("com.sun.xml.ws:jaxws-rt:4.0.0")
    // https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports
    implementation("net.sf.jasperreports:jasperreports:6.20.6")
    // https://mvnrepository.com/artifact/net.sf.barcode4j/barcode4j
    implementation("net.sf.barcode4j:barcode4j:2.1")
    // https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-all
    implementation("org.apache.xmlgraphics:batik-all:1.17")
    // https://mvnrepository.com/artifact/com.github.librepdf/openpdf
    implementation("com.github.librepdf:openpdf:1.3.30")
    compileOnly("org.projectlombok:lombok:1.18.30")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("roquiprinter.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
