//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 09:37:27 PM ECT
//

package ec.gob.sri.withhold.v200;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="infoTributaria" type="{}infoTributaria"/&gt;
 *         &lt;element name="infoCompRetencion"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fechaEmision" type="{}fechaEmision"/&gt;
 *                   &lt;element name="dirEstablecimiento" type="{}dirEstablecimiento" minOccurs="0"/&gt;
 *                   &lt;element name="contribuyenteEspecial" type="{}contribuyenteEspecial" minOccurs="0"/&gt;
 *                   &lt;element name="obligadoContabilidad" type="{}obligadoContabilidad" minOccurs="0"/&gt;
 *                   &lt;element name="tipoIdentificacionSujetoRetenido" type="{}tipoIdentificacionSujetoRetenido"/&gt;
 *                   &lt;element name="tipoSujetoRetenido" type="{}tipoSujetoRetenido" minOccurs="0"/&gt;
 *                   &lt;element name="parteRel" type="{}parteRel"/&gt;
 *                   &lt;element name="razonSocialSujetoRetenido" type="{}razonSocialSujetoRetenido"/&gt;
 *                   &lt;element name="identificacionSujetoRetenido" type="{}identificacionSujetoRetenido"/&gt;
 *                   &lt;element name="periodoFiscal" type="{}periodoFiscal"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="docsSustento"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="docSustento" type="{}docSustento" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="maquinaFiscal" type="{}maquinaFiscal" minOccurs="0"/&gt;
 *         &lt;element name="infoAdicional" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="campoAdicional" maxOccurs="15"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;&gt;campoAdicional"&gt;
 *                           &lt;attribute name="nombre" use="required" type="{}nombre" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="comprobante"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {
      "infoTributaria",
      "infoCompRetencion",
      "docsSustento",
      "maquinaFiscal",
      "infoAdicional"
    })
@XmlRootElement(name = "comprobanteRetencion")
public class ComprobanteRetencion {

  @XmlElement(required = true)
  protected InfoTributaria infoTributaria;

  @XmlElement(required = true)
  protected ComprobanteRetencion.InfoCompRetencion infoCompRetencion;

  @XmlElement(required = true)
  protected ComprobanteRetencion.DocsSustento docsSustento;

  protected MaquinaFiscal maquinaFiscal;
  protected ComprobanteRetencion.InfoAdicional infoAdicional;

  @XmlAttribute(name = "id")
  protected String id;

  @XmlAttribute(name = "version", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "NMTOKEN")
  protected String version;

  /**
   * Gets the value of the infoTributaria property.
   *
   * @return possible object is {@link InfoTributaria }
   */
  public InfoTributaria getInfoTributaria() {
    return infoTributaria;
  }

  /**
   * Sets the value of the infoTributaria property.
   *
   * @param value allowed object is {@link InfoTributaria }
   */
  public void setInfoTributaria(InfoTributaria value) {
    this.infoTributaria = value;
  }

  /**
   * Gets the value of the infoCompRetencion property.
   *
   * @return possible object is {@link ComprobanteRetencion.InfoCompRetencion }
   */
  public ComprobanteRetencion.InfoCompRetencion getInfoCompRetencion() {
    return infoCompRetencion;
  }

  /**
   * Sets the value of the infoCompRetencion property.
   *
   * @param value allowed object is {@link ComprobanteRetencion.InfoCompRetencion }
   */
  public void setInfoCompRetencion(ComprobanteRetencion.InfoCompRetencion value) {
    this.infoCompRetencion = value;
  }

  /**
   * Gets the value of the docsSustento property.
   *
   * @return possible object is {@link ComprobanteRetencion.DocsSustento }
   */
  public ComprobanteRetencion.DocsSustento getDocsSustento() {
    return docsSustento;
  }

  /**
   * Sets the value of the docsSustento property.
   *
   * @param value allowed object is {@link ComprobanteRetencion.DocsSustento }
   */
  public void setDocsSustento(ComprobanteRetencion.DocsSustento value) {
    this.docsSustento = value;
  }

  /**
   * Gets the value of the maquinaFiscal property.
   *
   * @return possible object is {@link MaquinaFiscal }
   */
  public MaquinaFiscal getMaquinaFiscal() {
    return maquinaFiscal;
  }

  /**
   * Sets the value of the maquinaFiscal property.
   *
   * @param value allowed object is {@link MaquinaFiscal }
   */
  public void setMaquinaFiscal(MaquinaFiscal value) {
    this.maquinaFiscal = value;
  }

  /**
   * Gets the value of the infoAdicional property.
   *
   * @return possible object is {@link ComprobanteRetencion.InfoAdicional }
   */
  public ComprobanteRetencion.InfoAdicional getInfoAdicional() {
    return infoAdicional;
  }

  /**
   * Sets the value of the infoAdicional property.
   *
   * @param value allowed object is {@link ComprobanteRetencion.InfoAdicional }
   */
  public void setInfoAdicional(ComprobanteRetencion.InfoAdicional value) {
    this.infoAdicional = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the version property.
   *
   * @return possible object is {@link String }
   */
  public String getVersion() {
    return version;
  }

  /**
   * Sets the value of the version property.
   *
   * @param value allowed object is {@link String }
   */
  public void setVersion(String value) {
    this.version = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="docSustento" type="{}docSustento" maxOccurs="unbounded"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"docSustento"})
  public static class DocsSustento {

    @XmlElement(required = true)
    protected List<DocSustento> docSustento;

    /**
     * Gets the value of the docSustento property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the docSustento property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getDocSustento().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link DocSustento }
     */
    public List<DocSustento> getDocSustento() {
      if (docSustento == null) {
        docSustento = new ArrayList<DocSustento>();
      }
      return this.docSustento;
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="campoAdicional" maxOccurs="15"&gt;
   *           &lt;complexType&gt;
   *             &lt;simpleContent&gt;
   *               &lt;extension base="&lt;&gt;campoAdicional"&gt;
   *                 &lt;attribute name="nombre" use="required" type="{}nombre" /&gt;
   *               &lt;/extension&gt;
   *             &lt;/simpleContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"campoAdicional"})
  public static class InfoAdicional {

    @XmlElement(required = true)
    protected List<ComprobanteRetencion.InfoAdicional.CampoAdicional> campoAdicional;

    /**
     * Gets the value of the campoAdicional property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the campoAdicional property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getCampoAdicional().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * ComprobanteRetencion.InfoAdicional.CampoAdicional }
     */
    public List<ComprobanteRetencion.InfoAdicional.CampoAdicional> getCampoAdicional() {
      if (campoAdicional == null) {
        campoAdicional = new ArrayList<ComprobanteRetencion.InfoAdicional.CampoAdicional>();
      }
      return this.campoAdicional;
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;&gt;campoAdicional"&gt;
     *       &lt;attribute name="nombre" use="required" type="{}nombre" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {"value"})
    public static class CampoAdicional {

      @XmlValue protected String value;

      @XmlAttribute(name = "nombre", required = true)
      protected String nombre;

      /**
       * Gets the value of the value property.
       *
       * @return possible object is {@link String }
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       *
       * @param value allowed object is {@link String }
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the nombre property.
       *
       * @return possible object is {@link String }
       */
      public String getNombre() {
        return nombre;
      }

      /**
       * Sets the value of the nombre property.
       *
       * @param value allowed object is {@link String }
       */
      public void setNombre(String value) {
        this.nombre = value;
      }
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="fechaEmision" type="{}fechaEmision"/&gt;
   *         &lt;element name="dirEstablecimiento" type="{}dirEstablecimiento" minOccurs="0"/&gt;
   *         &lt;element name="contribuyenteEspecial" type="{}contribuyenteEspecial" minOccurs="0"/&gt;
   *         &lt;element name="obligadoContabilidad" type="{}obligadoContabilidad" minOccurs="0"/&gt;
   *         &lt;element name="tipoIdentificacionSujetoRetenido" type="{}tipoIdentificacionSujetoRetenido"/&gt;
   *         &lt;element name="tipoSujetoRetenido" type="{}tipoSujetoRetenido" minOccurs="0"/&gt;
   *         &lt;element name="parteRel" type="{}parteRel"/&gt;
   *         &lt;element name="razonSocialSujetoRetenido" type="{}razonSocialSujetoRetenido"/&gt;
   *         &lt;element name="identificacionSujetoRetenido" type="{}identificacionSujetoRetenido"/&gt;
   *         &lt;element name="periodoFiscal" type="{}periodoFiscal"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {
        "fechaEmision",
        "dirEstablecimiento",
        "contribuyenteEspecial",
        "obligadoContabilidad",
        "tipoIdentificacionSujetoRetenido",
        "tipoSujetoRetenido",
        "parteRel",
        "razonSocialSujetoRetenido",
        "identificacionSujetoRetenido",
        "periodoFiscal"
      })
  public static class InfoCompRetencion {

    @XmlElement(required = true)
    protected String fechaEmision;

    protected String dirEstablecimiento;
    protected String contribuyenteEspecial;

    @XmlSchemaType(name = "string")
    protected ObligadoContabilidad obligadoContabilidad;

    @XmlElement(required = true)
    protected String tipoIdentificacionSujetoRetenido;

    protected String tipoSujetoRetenido;

    @XmlElement(required = true)
    protected String parteRel;

    @XmlElement(required = true)
    protected String razonSocialSujetoRetenido;

    @XmlElement(required = true)
    protected String identificacionSujetoRetenido;

    @XmlElement(required = true)
    protected String periodoFiscal;

    /**
     * Gets the value of the fechaEmision property.
     *
     * @return possible object is {@link String }
     */
    public String getFechaEmision() {
      return fechaEmision;
    }

    /**
     * Sets the value of the fechaEmision property.
     *
     * @param value allowed object is {@link String }
     */
    public void setFechaEmision(String value) {
      this.fechaEmision = value;
    }

    /**
     * Gets the value of the dirEstablecimiento property.
     *
     * @return possible object is {@link String }
     */
    public String getDirEstablecimiento() {
      return dirEstablecimiento;
    }

    /**
     * Sets the value of the dirEstablecimiento property.
     *
     * @param value allowed object is {@link String }
     */
    public void setDirEstablecimiento(String value) {
      this.dirEstablecimiento = value;
    }

    /**
     * Gets the value of the contribuyenteEspecial property.
     *
     * @return possible object is {@link String }
     */
    public String getContribuyenteEspecial() {
      return contribuyenteEspecial;
    }

    /**
     * Sets the value of the contribuyenteEspecial property.
     *
     * @param value allowed object is {@link String }
     */
    public void setContribuyenteEspecial(String value) {
      this.contribuyenteEspecial = value;
    }

    /**
     * Gets the value of the obligadoContabilidad property.
     *
     * @return possible object is {@link ObligadoContabilidad }
     */
    public ObligadoContabilidad getObligadoContabilidad() {
      return obligadoContabilidad;
    }

    /**
     * Sets the value of the obligadoContabilidad property.
     *
     * @param value allowed object is {@link ObligadoContabilidad }
     */
    public void setObligadoContabilidad(ObligadoContabilidad value) {
      this.obligadoContabilidad = value;
    }

    /**
     * Gets the value of the tipoIdentificacionSujetoRetenido property.
     *
     * @return possible object is {@link String }
     */
    public String getTipoIdentificacionSujetoRetenido() {
      return tipoIdentificacionSujetoRetenido;
    }

    /**
     * Sets the value of the tipoIdentificacionSujetoRetenido property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTipoIdentificacionSujetoRetenido(String value) {
      this.tipoIdentificacionSujetoRetenido = value;
    }

    /**
     * Gets the value of the tipoSujetoRetenido property.
     *
     * @return possible object is {@link String }
     */
    public String getTipoSujetoRetenido() {
      return tipoSujetoRetenido;
    }

    /**
     * Sets the value of the tipoSujetoRetenido property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTipoSujetoRetenido(String value) {
      this.tipoSujetoRetenido = value;
    }

    /**
     * Gets the value of the parteRel property.
     *
     * @return possible object is {@link String }
     */
    public String getParteRel() {
      return parteRel;
    }

    /**
     * Sets the value of the parteRel property.
     *
     * @param value allowed object is {@link String }
     */
    public void setParteRel(String value) {
      this.parteRel = value;
    }

    /**
     * Gets the value of the razonSocialSujetoRetenido property.
     *
     * @return possible object is {@link String }
     */
    public String getRazonSocialSujetoRetenido() {
      return razonSocialSujetoRetenido;
    }

    /**
     * Sets the value of the razonSocialSujetoRetenido property.
     *
     * @param value allowed object is {@link String }
     */
    public void setRazonSocialSujetoRetenido(String value) {
      this.razonSocialSujetoRetenido = value;
    }

    /**
     * Gets the value of the identificacionSujetoRetenido property.
     *
     * @return possible object is {@link String }
     */
    public String getIdentificacionSujetoRetenido() {
      return identificacionSujetoRetenido;
    }

    /**
     * Sets the value of the identificacionSujetoRetenido property.
     *
     * @param value allowed object is {@link String }
     */
    public void setIdentificacionSujetoRetenido(String value) {
      this.identificacionSujetoRetenido = value;
    }

    /**
     * Gets the value of the periodoFiscal property.
     *
     * @return possible object is {@link String }
     */
    public String getPeriodoFiscal() {
      return periodoFiscal;
    }

    /**
     * Sets the value of the periodoFiscal property.
     *
     * @param value allowed object is {@link String }
     */
    public void setPeriodoFiscal(String value) {
      this.periodoFiscal = value;
    }
  }
}
