//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 09:37:27 PM ECT
//

package ec.gob.sri.withhold.v200;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.math.BigDecimal;

/**
 * Java class for compraCajBanano complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="compraCajBanano"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numCajBan" type="{}numCajBan"/&gt;
 *         &lt;element name="precCajBan" type="{}precCajBan"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "compraCajBanano",
    propOrder = {"numCajBan", "precCajBan"})
public class CompraCajBanano {

  @XmlElement(required = true)
  protected String numCajBan;

  @XmlElement(required = true)
  protected BigDecimal precCajBan;

  /**
   * Gets the value of the numCajBan property.
   *
   * @return possible object is {@link String }
   */
  public String getNumCajBan() {
    return numCajBan;
  }

  /**
   * Sets the value of the numCajBan property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNumCajBan(String value) {
    this.numCajBan = value;
  }

  /**
   * Gets the value of the precCajBan property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getPrecCajBan() {
    return precCajBan;
  }

  /**
   * Sets the value of the precCajBan property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setPrecCajBan(BigDecimal value) {
    this.precCajBan = value;
  }
}
