//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 09:37:27 PM ECT
//

package ec.gob.sri.withhold.v200;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for detalleImpuestos complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="detalleImpuestos"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="detalleImpuesto" type="{}detalleImpuesto" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "detalleImpuestos",
    propOrder = {"detalleImpuesto"})
public class DetalleImpuestos {

  @XmlElement(required = true)
  protected List<DetalleImpuesto> detalleImpuesto;

  /**
   * Gets the value of the detalleImpuesto property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the detalleImpuesto property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getDetalleImpuesto().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link DetalleImpuesto }
   */
  public List<DetalleImpuesto> getDetalleImpuesto() {
    if (detalleImpuesto == null) {
      detalleImpuesto = new ArrayList<DetalleImpuesto>();
    }
    return this.detalleImpuesto;
  }
}
