//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.25 at 09:37:27 PM ECT 
//


package ec.gob.sri.withhold.v200;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dividendos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dividendos"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fechaPagoDiv" type="{}fecha"/&gt;
 *         &lt;element name="imRentaSoc" type="{}imRentaSoc"/&gt;
 *         &lt;element name="ejerFisUtDiv" type="{}ejerFisUtDiv"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dividendos", propOrder = {
    "fechaPagoDiv",
    "imRentaSoc",
    "ejerFisUtDiv"
})
public class Dividendos {

    @XmlElement(required = true)
    protected String fechaPagoDiv;
    @XmlElement(required = true)
    protected BigDecimal imRentaSoc;
    @XmlElement(required = true)
    protected String ejerFisUtDiv;

    /**
     * Gets the value of the fechaPagoDiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaPagoDiv() {
        return fechaPagoDiv;
    }

    /**
     * Sets the value of the fechaPagoDiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaPagoDiv(String value) {
        this.fechaPagoDiv = value;
    }

    /**
     * Gets the value of the imRentaSoc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImRentaSoc() {
        return imRentaSoc;
    }

    /**
     * Sets the value of the imRentaSoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImRentaSoc(BigDecimal value) {
        this.imRentaSoc = value;
    }

    /**
     * Gets the value of the ejerFisUtDiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjerFisUtDiv() {
        return ejerFisUtDiv;
    }

    /**
     * Sets the value of the ejerFisUtDiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjerFisUtDiv(String value) {
        this.ejerFisUtDiv = value;
    }

}
