//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.25 at 09:37:27 PM ECT 
//


package ec.gob.sri.withhold.v200;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ec.gob.sri.withhold.v200 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ec.gob.sri.withhold.v200
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComprobanteRetencion }
     * 
     */
    public ComprobanteRetencion createComprobanteRetencion() {
        return new ComprobanteRetencion();
    }

    /**
     * Create an instance of {@link Reembolsos }
     * 
     */
    public Reembolsos createReembolsos() {
        return new Reembolsos();
    }

    /**
     * Create an instance of {@link ComprobanteRetencion.InfoAdicional }
     * 
     */
    public ComprobanteRetencion.InfoAdicional createComprobanteRetencionInfoAdicional() {
        return new ComprobanteRetencion.InfoAdicional();
    }

    /**
     * Create an instance of {@link InfoTributaria }
     * 
     */
    public InfoTributaria createInfoTributaria() {
        return new InfoTributaria();
    }

    /**
     * Create an instance of {@link ComprobanteRetencion.InfoCompRetencion }
     * 
     */
    public ComprobanteRetencion.InfoCompRetencion createComprobanteRetencionInfoCompRetencion() {
        return new ComprobanteRetencion.InfoCompRetencion();
    }

    /**
     * Create an instance of {@link ComprobanteRetencion.DocsSustento }
     * 
     */
    public ComprobanteRetencion.DocsSustento createComprobanteRetencionDocsSustento() {
        return new ComprobanteRetencion.DocsSustento();
    }

    /**
     * Create an instance of {@link MaquinaFiscal }
     * 
     */
    public MaquinaFiscal createMaquinaFiscal() {
        return new MaquinaFiscal();
    }

    /**
     * Create an instance of {@link ImpuestoDocSustento }
     * 
     */
    public ImpuestoDocSustento createImpuestoDocSustento() {
        return new ImpuestoDocSustento();
    }

    /**
     * Create an instance of {@link Dividendos }
     * 
     */
    public Dividendos createDividendos() {
        return new Dividendos();
    }

    /**
     * Create an instance of {@link CompraCajBanano }
     * 
     */
    public CompraCajBanano createCompraCajBanano() {
        return new CompraCajBanano();
    }

    /**
     * Create an instance of {@link DetalleImpuesto }
     * 
     */
    public DetalleImpuesto createDetalleImpuesto() {
        return new DetalleImpuesto();
    }

    /**
     * Create an instance of {@link DetalleImpuestos }
     * 
     */
    public DetalleImpuestos createDetalleImpuestos() {
        return new DetalleImpuestos();
    }

    /**
     * Create an instance of {@link ImpuestosDocSustento }
     * 
     */
    public ImpuestosDocSustento createImpuestosDocSustento() {
        return new ImpuestosDocSustento();
    }

    /**
     * Create an instance of {@link Retencion }
     * 
     */
    public Retencion createRetencion() {
        return new Retencion();
    }

    /**
     * Create an instance of {@link Retenciones }
     * 
     */
    public Retenciones createRetenciones() {
        return new Retenciones();
    }

    /**
     * Create an instance of {@link Pago }
     * 
     */
    public Pago createPago() {
        return new Pago();
    }

    /**
     * Create an instance of {@link Pagos }
     * 
     */
    public Pagos createPagos() {
        return new Pagos();
    }

    /**
     * Create an instance of {@link DocSustento }
     * 
     */
    public DocSustento createDocSustento() {
        return new DocSustento();
    }

    /**
     * Create an instance of {@link Reembolsos.ReembolsoDetalle }
     * 
     */
    public Reembolsos.ReembolsoDetalle createReembolsosReembolsoDetalle() {
        return new Reembolsos.ReembolsoDetalle();
    }

    /**
     * Create an instance of {@link ComprobanteRetencion.InfoAdicional.CampoAdicional }
     * 
     */
    public ComprobanteRetencion.InfoAdicional.CampoAdicional createComprobanteRetencionInfoAdicionalCampoAdicional() {
        return new ComprobanteRetencion.InfoAdicional.CampoAdicional();
    }

}
