//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 09:24:44 PM ECT
//

package ec.gob.sri.note.credit.v110;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="compensacion" type="{}compensacion" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"compensacion"})
@XmlRootElement(name = "compensaciones")
public class Compensaciones {

  @XmlElement(required = true)
  protected List<Compensacion> compensacion;

  /**
   * Gets the value of the compensacion property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the compensacion property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getCompensacion().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Compensacion }
   */
  public List<Compensacion> getCompensacion() {
    if (compensacion == null) {
      compensacion = new ArrayList<Compensacion>();
    }
    return this.compensacion;
  }
}
