//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 09:24:44 PM ECT
//

package ec.gob.sri.note.credit.v110;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Detalle de una nota de credito.
 *
 * <p>Java class for detalle complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="detalle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="motivoModificacion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "detalle",
    propOrder = {"motivoModificacion"})
public class Detalle {

  @XmlElement(required = true)
  protected String motivoModificacion;

  /**
   * Gets the value of the motivoModificacion property.
   *
   * @return possible object is {@link String }
   */
  public String getMotivoModificacion() {
    return motivoModificacion;
  }

  /**
   * Sets the value of the motivoModificacion property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMotivoModificacion(String value) {
    this.motivoModificacion = value;
  }
}
