//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 09:24:44 PM ECT
//

package ec.gob.sri.note.credit.v110;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="infoTributaria" type="{}infoTributaria"/&gt;
 *         &lt;element name="infoNotaCredito"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fechaEmision" type="{}fechaEmision"/&gt;
 *                   &lt;element name="dirEstablecimiento" type="{}dirEstablecimiento" minOccurs="0"/&gt;
 *                   &lt;element name="tipoIdentificacionComprador" type="{}tipoIdentificacionComprador"/&gt;
 *                   &lt;element name="razonSocialComprador" type="{}razonSocialComprador"/&gt;
 *                   &lt;element name="identificacionComprador" type="{}identificacionComprador"/&gt;
 *                   &lt;element name="contribuyenteEspecial" type="{}contribuyenteEspecial" minOccurs="0"/&gt;
 *                   &lt;element name="obligadoContabilidad" type="{}obligadoContabilidad" minOccurs="0"/&gt;
 *                   &lt;element name="rise" type="{}rise" minOccurs="0"/&gt;
 *                   &lt;element name="codDocModificado" type="{}codDocModificado"/&gt;
 *                   &lt;element name="numDocModificado" type="{}numDocModificado"/&gt;
 *                   &lt;element name="fechaEmisionDocSustento" type="{}fechaEmisionDocSustento"/&gt;
 *                   &lt;element name="totalSinImpuestos" type="{}totalSinImpuestos"/&gt;
 *                   &lt;element ref="{}compensaciones" minOccurs="0"/&gt;
 *                   &lt;element name="valorModificacion" type="{}valorModificacion"/&gt;
 *                   &lt;element name="moneda" type="{}moneda" minOccurs="0"/&gt;
 *                   &lt;element ref="{}totalConImpuestos"/&gt;
 *                   &lt;element name="motivo" type="{}motivo"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="detalles"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="detalle" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="codigoInterno" type="{}codigoInterno" minOccurs="0"/&gt;
 *                             &lt;element name="codigoAdicional" type="{}codigoAdicional" minOccurs="0"/&gt;
 *                             &lt;element name="descripcion" type="{}descripcion"/&gt;
 *                             &lt;element name="cantidad" type="{}cantidad"/&gt;
 *                             &lt;element name="precioUnitario" type="{}precioUnitario"/&gt;
 *                             &lt;element name="descuento" type="{}descuento" minOccurs="0"/&gt;
 *                             &lt;element name="precioTotalSinImpuesto" type="{}precioTotalSinImpuesto"/&gt;
 *                             &lt;element name="detallesAdicionales" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="detAdicional" maxOccurs="3"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;attribute name="nombre" use="required"&gt;
 *                                                 &lt;simpleType&gt;
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                                     &lt;minLength value="1"/&gt;
 *                                                     &lt;maxLength value="300"/&gt;
 *                                                   &lt;/restriction&gt;
 *                                                 &lt;/simpleType&gt;
 *                                               &lt;/attribute&gt;
 *                                               &lt;attribute name="valor" use="required"&gt;
 *                                                 &lt;simpleType&gt;
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                                     &lt;minLength value="1"/&gt;
 *                                                     &lt;maxLength value="300"/&gt;
 *                                                   &lt;/restriction&gt;
 *                                                 &lt;/simpleType&gt;
 *                                               &lt;/attribute&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="impuestos"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="impuesto" type="{}impuesto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="maquinaFiscal" type="{}maquinaFiscal" minOccurs="0"/&gt;
 *         &lt;element name="infoAdicional" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="campoAdicional" maxOccurs="15"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;&gt;campoAdicional"&gt;
 *                           &lt;attribute name="nombre" use="required" type="{}nombre" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="comprobante"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"infoTributaria", "infoNotaCredito", "detalles", "maquinaFiscal", "infoAdicional"})
@XmlRootElement(name = "notaCredito")
public class NotaCredito {

  @XmlElement(required = true)
  protected InfoTributaria infoTributaria;

  @XmlElement(required = true)
  protected NotaCredito.InfoNotaCredito infoNotaCredito;

  @XmlElement(required = true)
  protected NotaCredito.Detalles detalles;

  protected MaquinaFiscal maquinaFiscal;
  protected NotaCredito.InfoAdicional infoAdicional;

  @XmlAttribute(name = "id", required = true)
  protected String id;

  @XmlAttribute(name = "version", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "NMTOKEN")
  protected String version;

  /**
   * Gets the value of the infoTributaria property.
   *
   * @return possible object is {@link InfoTributaria }
   */
  public InfoTributaria getInfoTributaria() {
    return infoTributaria;
  }

  /**
   * Sets the value of the infoTributaria property.
   *
   * @param value allowed object is {@link InfoTributaria }
   */
  public void setInfoTributaria(InfoTributaria value) {
    this.infoTributaria = value;
  }

  /**
   * Gets the value of the infoNotaCredito property.
   *
   * @return possible object is {@link NotaCredito.InfoNotaCredito }
   */
  public NotaCredito.InfoNotaCredito getInfoNotaCredito() {
    return infoNotaCredito;
  }

  /**
   * Sets the value of the infoNotaCredito property.
   *
   * @param value allowed object is {@link NotaCredito.InfoNotaCredito }
   */
  public void setInfoNotaCredito(NotaCredito.InfoNotaCredito value) {
    this.infoNotaCredito = value;
  }

  /**
   * Gets the value of the detalles property.
   *
   * @return possible object is {@link NotaCredito.Detalles }
   */
  public NotaCredito.Detalles getDetalles() {
    return detalles;
  }

  /**
   * Sets the value of the detalles property.
   *
   * @param value allowed object is {@link NotaCredito.Detalles }
   */
  public void setDetalles(NotaCredito.Detalles value) {
    this.detalles = value;
  }

  /**
   * Gets the value of the maquinaFiscal property.
   *
   * @return possible object is {@link MaquinaFiscal }
   */
  public MaquinaFiscal getMaquinaFiscal() {
    return maquinaFiscal;
  }

  /**
   * Sets the value of the maquinaFiscal property.
   *
   * @param value allowed object is {@link MaquinaFiscal }
   */
  public void setMaquinaFiscal(MaquinaFiscal value) {
    this.maquinaFiscal = value;
  }

  /**
   * Gets the value of the infoAdicional property.
   *
   * @return possible object is {@link NotaCredito.InfoAdicional }
   */
  public NotaCredito.InfoAdicional getInfoAdicional() {
    return infoAdicional;
  }

  /**
   * Sets the value of the infoAdicional property.
   *
   * @param value allowed object is {@link NotaCredito.InfoAdicional }
   */
  public void setInfoAdicional(NotaCredito.InfoAdicional value) {
    this.infoAdicional = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the version property.
   *
   * @return possible object is {@link String }
   */
  public String getVersion() {
    return version;
  }

  /**
   * Sets the value of the version property.
   *
   * @param value allowed object is {@link String }
   */
  public void setVersion(String value) {
    this.version = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="detalle" maxOccurs="unbounded"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;sequence&gt;
   *                   &lt;element name="codigoInterno" type="{}codigoInterno" minOccurs="0"/&gt;
   *                   &lt;element name="codigoAdicional" type="{}codigoAdicional" minOccurs="0"/&gt;
   *                   &lt;element name="descripcion" type="{}descripcion"/&gt;
   *                   &lt;element name="cantidad" type="{}cantidad"/&gt;
   *                   &lt;element name="precioUnitario" type="{}precioUnitario"/&gt;
   *                   &lt;element name="descuento" type="{}descuento" minOccurs="0"/&gt;
   *                   &lt;element name="precioTotalSinImpuesto" type="{}precioTotalSinImpuesto"/&gt;
   *                   &lt;element name="detallesAdicionales" minOccurs="0"&gt;
   *                     &lt;complexType&gt;
   *                       &lt;complexContent&gt;
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                           &lt;sequence&gt;
   *                             &lt;element name="detAdicional" maxOccurs="3"&gt;
   *                               &lt;complexType&gt;
   *                                 &lt;complexContent&gt;
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                                     &lt;attribute name="nombre" use="required"&gt;
   *                                       &lt;simpleType&gt;
   *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
   *                                           &lt;minLength value="1"/&gt;
   *                                           &lt;maxLength value="300"/&gt;
   *                                         &lt;/restriction&gt;
   *                                       &lt;/simpleType&gt;
   *                                     &lt;/attribute&gt;
   *                                     &lt;attribute name="valor" use="required"&gt;
   *                                       &lt;simpleType&gt;
   *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
   *                                           &lt;minLength value="1"/&gt;
   *                                           &lt;maxLength value="300"/&gt;
   *                                         &lt;/restriction&gt;
   *                                       &lt;/simpleType&gt;
   *                                     &lt;/attribute&gt;
   *                                   &lt;/restriction&gt;
   *                                 &lt;/complexContent&gt;
   *                               &lt;/complexType&gt;
   *                             &lt;/element&gt;
   *                           &lt;/sequence&gt;
   *                         &lt;/restriction&gt;
   *                       &lt;/complexContent&gt;
   *                     &lt;/complexType&gt;
   *                   &lt;/element&gt;
   *                   &lt;element name="impuestos"&gt;
   *                     &lt;complexType&gt;
   *                       &lt;complexContent&gt;
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                           &lt;sequence&gt;
   *                             &lt;element name="impuesto" type="{}impuesto" maxOccurs="unbounded" minOccurs="0"/&gt;
   *                           &lt;/sequence&gt;
   *                         &lt;/restriction&gt;
   *                       &lt;/complexContent&gt;
   *                     &lt;/complexType&gt;
   *                   &lt;/element&gt;
   *                 &lt;/sequence&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"detalle"})
  public static class Detalles {

    @XmlElement(required = true)
    protected List<NotaCredito.Detalles.Detalle> detalle;

    /**
     * Gets the value of the detalle property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the detalle property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getDetalle().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * NotaCredito.Detalles.Detalle }
     */
    public List<NotaCredito.Detalles.Detalle> getDetalle() {
      if (detalle == null) {
        detalle = new ArrayList<NotaCredito.Detalles.Detalle>();
      }
      return this.detalle;
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="codigoInterno" type="{}codigoInterno" minOccurs="0"/&gt;
     *         &lt;element name="codigoAdicional" type="{}codigoAdicional" minOccurs="0"/&gt;
     *         &lt;element name="descripcion" type="{}descripcion"/&gt;
     *         &lt;element name="cantidad" type="{}cantidad"/&gt;
     *         &lt;element name="precioUnitario" type="{}precioUnitario"/&gt;
     *         &lt;element name="descuento" type="{}descuento" minOccurs="0"/&gt;
     *         &lt;element name="precioTotalSinImpuesto" type="{}precioTotalSinImpuesto"/&gt;
     *         &lt;element name="detallesAdicionales" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="detAdicional" maxOccurs="3"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="nombre" use="required"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                 &lt;minLength value="1"/&gt;
     *                                 &lt;maxLength value="300"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                           &lt;attribute name="valor" use="required"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                 &lt;minLength value="1"/&gt;
     *                                 &lt;maxLength value="300"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="impuestos"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="impuesto" type="{}impuesto" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {
          "codigoInterno",
          "codigoAdicional",
          "descripcion",
          "cantidad",
          "precioUnitario",
          "descuento",
          "precioTotalSinImpuesto",
          "detallesAdicionales",
          "impuestos"
        })
    public static class Detalle {

      protected String codigoInterno;
      protected String codigoAdicional;

      @XmlElement(required = true)
      protected String descripcion;

      @XmlElement(required = true)
      protected BigDecimal cantidad;

      @XmlElement(required = true)
      protected BigDecimal precioUnitario;

      protected BigDecimal descuento;

      @XmlElement(required = true)
      protected BigDecimal precioTotalSinImpuesto;

      protected NotaCredito.Detalles.Detalle.DetallesAdicionales detallesAdicionales;

      @XmlElement(required = true)
      protected NotaCredito.Detalles.Detalle.Impuestos impuestos;

      /**
       * Gets the value of the codigoInterno property.
       *
       * @return possible object is {@link String }
       */
      public String getCodigoInterno() {
        return codigoInterno;
      }

      /**
       * Sets the value of the codigoInterno property.
       *
       * @param value allowed object is {@link String }
       */
      public void setCodigoInterno(String value) {
        this.codigoInterno = value;
      }

      /**
       * Gets the value of the codigoAdicional property.
       *
       * @return possible object is {@link String }
       */
      public String getCodigoAdicional() {
        return codigoAdicional;
      }

      /**
       * Sets the value of the codigoAdicional property.
       *
       * @param value allowed object is {@link String }
       */
      public void setCodigoAdicional(String value) {
        this.codigoAdicional = value;
      }

      /**
       * Gets the value of the descripcion property.
       *
       * @return possible object is {@link String }
       */
      public String getDescripcion() {
        return descripcion;
      }

      /**
       * Sets the value of the descripcion property.
       *
       * @param value allowed object is {@link String }
       */
      public void setDescripcion(String value) {
        this.descripcion = value;
      }

      /**
       * Gets the value of the cantidad property.
       *
       * @return possible object is {@link BigDecimal }
       */
      public BigDecimal getCantidad() {
        return cantidad;
      }

      /**
       * Sets the value of the cantidad property.
       *
       * @param value allowed object is {@link BigDecimal }
       */
      public void setCantidad(BigDecimal value) {
        this.cantidad = value;
      }

      /**
       * Gets the value of the precioUnitario property.
       *
       * @return possible object is {@link BigDecimal }
       */
      public BigDecimal getPrecioUnitario() {
        return precioUnitario;
      }

      /**
       * Sets the value of the precioUnitario property.
       *
       * @param value allowed object is {@link BigDecimal }
       */
      public void setPrecioUnitario(BigDecimal value) {
        this.precioUnitario = value;
      }

      /**
       * Gets the value of the descuento property.
       *
       * @return possible object is {@link BigDecimal }
       */
      public BigDecimal getDescuento() {
        return descuento;
      }

      /**
       * Sets the value of the descuento property.
       *
       * @param value allowed object is {@link BigDecimal }
       */
      public void setDescuento(BigDecimal value) {
        this.descuento = value;
      }

      /**
       * Gets the value of the precioTotalSinImpuesto property.
       *
       * @return possible object is {@link BigDecimal }
       */
      public BigDecimal getPrecioTotalSinImpuesto() {
        return precioTotalSinImpuesto;
      }

      /**
       * Sets the value of the precioTotalSinImpuesto property.
       *
       * @param value allowed object is {@link BigDecimal }
       */
      public void setPrecioTotalSinImpuesto(BigDecimal value) {
        this.precioTotalSinImpuesto = value;
      }

      /**
       * Gets the value of the detallesAdicionales property.
       *
       * @return possible object is {@link NotaCredito.Detalles.Detalle.DetallesAdicionales }
       */
      public NotaCredito.Detalles.Detalle.DetallesAdicionales getDetallesAdicionales() {
        return detallesAdicionales;
      }

      /**
       * Sets the value of the detallesAdicionales property.
       *
       * @param value allowed object is {@link NotaCredito.Detalles.Detalle.DetallesAdicionales }
       */
      public void setDetallesAdicionales(NotaCredito.Detalles.Detalle.DetallesAdicionales value) {
        this.detallesAdicionales = value;
      }

      /**
       * Gets the value of the impuestos property.
       *
       * @return possible object is {@link NotaCredito.Detalles.Detalle.Impuestos }
       */
      public NotaCredito.Detalles.Detalle.Impuestos getImpuestos() {
        return impuestos;
      }

      /**
       * Sets the value of the impuestos property.
       *
       * @param value allowed object is {@link NotaCredito.Detalles.Detalle.Impuestos }
       */
      public void setImpuestos(NotaCredito.Detalles.Detalle.Impuestos value) {
        this.impuestos = value;
      }

      /**
       * Java class for anonymous complex type.
       *
       * <p>The following schema fragment specifies the expected content contained within this
       * class.
       *
       * <pre>
       * &lt;complexType&gt;
       *   &lt;complexContent&gt;
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
       *       &lt;sequence&gt;
       *         &lt;element name="detAdicional" maxOccurs="3"&gt;
       *           &lt;complexType&gt;
       *             &lt;complexContent&gt;
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
       *                 &lt;attribute name="nombre" use="required"&gt;
       *                   &lt;simpleType&gt;
       *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
       *                       &lt;minLength value="1"/&gt;
       *                       &lt;maxLength value="300"/&gt;
       *                     &lt;/restriction&gt;
       *                   &lt;/simpleType&gt;
       *                 &lt;/attribute&gt;
       *                 &lt;attribute name="valor" use="required"&gt;
       *                   &lt;simpleType&gt;
       *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
       *                       &lt;minLength value="1"/&gt;
       *                       &lt;maxLength value="300"/&gt;
       *                     &lt;/restriction&gt;
       *                   &lt;/simpleType&gt;
       *                 &lt;/attribute&gt;
       *               &lt;/restriction&gt;
       *             &lt;/complexContent&gt;
       *           &lt;/complexType&gt;
       *         &lt;/element&gt;
       *       &lt;/sequence&gt;
       *     &lt;/restriction&gt;
       *   &lt;/complexContent&gt;
       * &lt;/complexType&gt;
       * </pre>
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(
          name = "",
          propOrder = {"detAdicional"})
      public static class DetallesAdicionales {

        @XmlElement(required = true)
        protected List<NotaCredito.Detalles.Detalle.DetallesAdicionales.DetAdicional> detAdicional;

        /**
         * Gets the value of the detAdicional property.
         *
         * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the detAdicional property.
         *
         * <p>For example, to add a new item, do as follows:
         *
         * <pre>
         *    getDetAdicional().add(newItem);
         * </pre>
         *
         * <p>Objects of the following type(s) are allowed in the list {@link
         * NotaCredito.Detalles.Detalle.DetallesAdicionales.DetAdicional }
         */
        public List<NotaCredito.Detalles.Detalle.DetallesAdicionales.DetAdicional>
            getDetAdicional() {
          if (detAdicional == null) {
            detAdicional =
                new ArrayList<NotaCredito.Detalles.Detalle.DetallesAdicionales.DetAdicional>();
          }
          return this.detAdicional;
        }

        /**
         * Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this
         * class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="nombre" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="300"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="valor" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;minLength value="1"/&gt;
         *             &lt;maxLength value="300"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DetAdicional {

          @XmlAttribute(name = "nombre", required = true)
          protected String nombre;

          @XmlAttribute(name = "valor", required = true)
          protected String valor;

          /**
           * Gets the value of the nombre property.
           *
           * @return possible object is {@link String }
           */
          public String getNombre() {
            return nombre;
          }

          /**
           * Sets the value of the nombre property.
           *
           * @param value allowed object is {@link String }
           */
          public void setNombre(String value) {
            this.nombre = value;
          }

          /**
           * Gets the value of the valor property.
           *
           * @return possible object is {@link String }
           */
          public String getValor() {
            return valor;
          }

          /**
           * Sets the value of the valor property.
           *
           * @param value allowed object is {@link String }
           */
          public void setValor(String value) {
            this.valor = value;
          }
        }
      }

      /**
       * Java class for anonymous complex type.
       *
       * <p>The following schema fragment specifies the expected content contained within this
       * class.
       *
       * <pre>
       * &lt;complexType&gt;
       *   &lt;complexContent&gt;
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
       *       &lt;sequence&gt;
       *         &lt;element name="impuesto" type="{}impuesto" maxOccurs="unbounded" minOccurs="0"/&gt;
       *       &lt;/sequence&gt;
       *     &lt;/restriction&gt;
       *   &lt;/complexContent&gt;
       * &lt;/complexType&gt;
       * </pre>
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(
          name = "",
          propOrder = {"impuesto"})
      public static class Impuestos {

        protected List<Impuesto> impuesto;

        /**
         * Gets the value of the impuesto property.
         *
         * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the impuesto property.
         *
         * <p>For example, to add a new item, do as follows:
         *
         * <pre>
         *    getImpuesto().add(newItem);
         * </pre>
         *
         * <p>Objects of the following type(s) are allowed in the list {@link Impuesto }
         */
        public List<Impuesto> getImpuesto() {
          if (impuesto == null) {
            impuesto = new ArrayList<Impuesto>();
          }
          return this.impuesto;
        }
      }
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="campoAdicional" maxOccurs="15"&gt;
   *           &lt;complexType&gt;
   *             &lt;simpleContent&gt;
   *               &lt;extension base="&lt;&gt;campoAdicional"&gt;
   *                 &lt;attribute name="nombre" use="required" type="{}nombre" /&gt;
   *               &lt;/extension&gt;
   *             &lt;/simpleContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"campoAdicional"})
  public static class InfoAdicional {

    @XmlElement(required = true)
    protected List<NotaCredito.InfoAdicional.CampoAdicional> campoAdicional;

    /**
     * Gets the value of the campoAdicional property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the campoAdicional property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getCampoAdicional().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * NotaCredito.InfoAdicional.CampoAdicional }
     */
    public List<NotaCredito.InfoAdicional.CampoAdicional> getCampoAdicional() {
      if (campoAdicional == null) {
        campoAdicional = new ArrayList<NotaCredito.InfoAdicional.CampoAdicional>();
      }
      return this.campoAdicional;
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;&gt;campoAdicional"&gt;
     *       &lt;attribute name="nombre" use="required" type="{}nombre" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {"value"})
    public static class CampoAdicional {

      @XmlValue protected String value;

      @XmlAttribute(name = "nombre", required = true)
      protected String nombre;

      /**
       * Gets the value of the value property.
       *
       * @return possible object is {@link String }
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       *
       * @param value allowed object is {@link String }
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the nombre property.
       *
       * @return possible object is {@link String }
       */
      public String getNombre() {
        return nombre;
      }

      /**
       * Sets the value of the nombre property.
       *
       * @param value allowed object is {@link String }
       */
      public void setNombre(String value) {
        this.nombre = value;
      }
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="fechaEmision" type="{}fechaEmision"/&gt;
   *         &lt;element name="dirEstablecimiento" type="{}dirEstablecimiento" minOccurs="0"/&gt;
   *         &lt;element name="tipoIdentificacionComprador" type="{}tipoIdentificacionComprador"/&gt;
   *         &lt;element name="razonSocialComprador" type="{}razonSocialComprador"/&gt;
   *         &lt;element name="identificacionComprador" type="{}identificacionComprador"/&gt;
   *         &lt;element name="contribuyenteEspecial" type="{}contribuyenteEspecial" minOccurs="0"/&gt;
   *         &lt;element name="obligadoContabilidad" type="{}obligadoContabilidad" minOccurs="0"/&gt;
   *         &lt;element name="rise" type="{}rise" minOccurs="0"/&gt;
   *         &lt;element name="codDocModificado" type="{}codDocModificado"/&gt;
   *         &lt;element name="numDocModificado" type="{}numDocModificado"/&gt;
   *         &lt;element name="fechaEmisionDocSustento" type="{}fechaEmisionDocSustento"/&gt;
   *         &lt;element name="totalSinImpuestos" type="{}totalSinImpuestos"/&gt;
   *         &lt;element ref="{}compensaciones" minOccurs="0"/&gt;
   *         &lt;element name="valorModificacion" type="{}valorModificacion"/&gt;
   *         &lt;element name="moneda" type="{}moneda" minOccurs="0"/&gt;
   *         &lt;element ref="{}totalConImpuestos"/&gt;
   *         &lt;element name="motivo" type="{}motivo"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {
        "fechaEmision",
        "dirEstablecimiento",
        "tipoIdentificacionComprador",
        "razonSocialComprador",
        "identificacionComprador",
        "contribuyenteEspecial",
        "obligadoContabilidad",
        "rise",
        "codDocModificado",
        "numDocModificado",
        "fechaEmisionDocSustento",
        "totalSinImpuestos",
        "compensaciones",
        "valorModificacion",
        "moneda",
        "totalConImpuestos",
        "motivo"
      })
  public static class InfoNotaCredito {

    @XmlElement(required = true)
    protected String fechaEmision;

    protected String dirEstablecimiento;

    @XmlElement(required = true)
    protected String tipoIdentificacionComprador;

    @XmlElement(required = true)
    protected String razonSocialComprador;

    @XmlElement(required = true)
    protected String identificacionComprador;

    protected String contribuyenteEspecial;

    @XmlSchemaType(name = "string")
    protected ObligadoContabilidad obligadoContabilidad;

    protected String rise;

    @XmlElement(required = true)
    protected String codDocModificado;

    @XmlElement(required = true)
    protected String numDocModificado;

    @XmlElement(required = true)
    protected String fechaEmisionDocSustento;

    @XmlElement(required = true)
    protected BigDecimal totalSinImpuestos;

    protected Compensaciones compensaciones;

    @XmlElement(required = true)
    protected BigDecimal valorModificacion;

    protected String moneda;

    @XmlElement(required = true)
    protected TotalConImpuestos totalConImpuestos;

    @XmlElement(required = true)
    protected String motivo;

    /**
     * Gets the value of the fechaEmision property.
     *
     * @return possible object is {@link String }
     */
    public String getFechaEmision() {
      return fechaEmision;
    }

    /**
     * Sets the value of the fechaEmision property.
     *
     * @param value allowed object is {@link String }
     */
    public void setFechaEmision(String value) {
      this.fechaEmision = value;
    }

    /**
     * Gets the value of the dirEstablecimiento property.
     *
     * @return possible object is {@link String }
     */
    public String getDirEstablecimiento() {
      return dirEstablecimiento;
    }

    /**
     * Sets the value of the dirEstablecimiento property.
     *
     * @param value allowed object is {@link String }
     */
    public void setDirEstablecimiento(String value) {
      this.dirEstablecimiento = value;
    }

    /**
     * Gets the value of the tipoIdentificacionComprador property.
     *
     * @return possible object is {@link String }
     */
    public String getTipoIdentificacionComprador() {
      return tipoIdentificacionComprador;
    }

    /**
     * Sets the value of the tipoIdentificacionComprador property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTipoIdentificacionComprador(String value) {
      this.tipoIdentificacionComprador = value;
    }

    /**
     * Gets the value of the razonSocialComprador property.
     *
     * @return possible object is {@link String }
     */
    public String getRazonSocialComprador() {
      return razonSocialComprador;
    }

    /**
     * Sets the value of the razonSocialComprador property.
     *
     * @param value allowed object is {@link String }
     */
    public void setRazonSocialComprador(String value) {
      this.razonSocialComprador = value;
    }

    /**
     * Gets the value of the identificacionComprador property.
     *
     * @return possible object is {@link String }
     */
    public String getIdentificacionComprador() {
      return identificacionComprador;
    }

    /**
     * Sets the value of the identificacionComprador property.
     *
     * @param value allowed object is {@link String }
     */
    public void setIdentificacionComprador(String value) {
      this.identificacionComprador = value;
    }

    /**
     * Gets the value of the contribuyenteEspecial property.
     *
     * @return possible object is {@link String }
     */
    public String getContribuyenteEspecial() {
      return contribuyenteEspecial;
    }

    /**
     * Sets the value of the contribuyenteEspecial property.
     *
     * @param value allowed object is {@link String }
     */
    public void setContribuyenteEspecial(String value) {
      this.contribuyenteEspecial = value;
    }

    /**
     * Gets the value of the obligadoContabilidad property.
     *
     * @return possible object is {@link ObligadoContabilidad }
     */
    public ObligadoContabilidad getObligadoContabilidad() {
      return obligadoContabilidad;
    }

    /**
     * Sets the value of the obligadoContabilidad property.
     *
     * @param value allowed object is {@link ObligadoContabilidad }
     */
    public void setObligadoContabilidad(ObligadoContabilidad value) {
      this.obligadoContabilidad = value;
    }

    /**
     * Gets the value of the rise property.
     *
     * @return possible object is {@link String }
     */
    public String getRise() {
      return rise;
    }

    /**
     * Sets the value of the rise property.
     *
     * @param value allowed object is {@link String }
     */
    public void setRise(String value) {
      this.rise = value;
    }

    /**
     * Gets the value of the codDocModificado property.
     *
     * @return possible object is {@link String }
     */
    public String getCodDocModificado() {
      return codDocModificado;
    }

    /**
     * Sets the value of the codDocModificado property.
     *
     * @param value allowed object is {@link String }
     */
    public void setCodDocModificado(String value) {
      this.codDocModificado = value;
    }

    /**
     * Gets the value of the numDocModificado property.
     *
     * @return possible object is {@link String }
     */
    public String getNumDocModificado() {
      return numDocModificado;
    }

    /**
     * Sets the value of the numDocModificado property.
     *
     * @param value allowed object is {@link String }
     */
    public void setNumDocModificado(String value) {
      this.numDocModificado = value;
    }

    /**
     * Gets the value of the fechaEmisionDocSustento property.
     *
     * @return possible object is {@link String }
     */
    public String getFechaEmisionDocSustento() {
      return fechaEmisionDocSustento;
    }

    /**
     * Sets the value of the fechaEmisionDocSustento property.
     *
     * @param value allowed object is {@link String }
     */
    public void setFechaEmisionDocSustento(String value) {
      this.fechaEmisionDocSustento = value;
    }

    /**
     * Gets the value of the totalSinImpuestos property.
     *
     * @return possible object is {@link BigDecimal }
     */
    public BigDecimal getTotalSinImpuestos() {
      return totalSinImpuestos;
    }

    /**
     * Sets the value of the totalSinImpuestos property.
     *
     * @param value allowed object is {@link BigDecimal }
     */
    public void setTotalSinImpuestos(BigDecimal value) {
      this.totalSinImpuestos = value;
    }

    /**
     * Gets the value of the compensaciones property.
     *
     * @return possible object is {@link Compensaciones }
     */
    public Compensaciones getCompensaciones() {
      return compensaciones;
    }

    /**
     * Sets the value of the compensaciones property.
     *
     * @param value allowed object is {@link Compensaciones }
     */
    public void setCompensaciones(Compensaciones value) {
      this.compensaciones = value;
    }

    /**
     * Gets the value of the valorModificacion property.
     *
     * @return possible object is {@link BigDecimal }
     */
    public BigDecimal getValorModificacion() {
      return valorModificacion;
    }

    /**
     * Sets the value of the valorModificacion property.
     *
     * @param value allowed object is {@link BigDecimal }
     */
    public void setValorModificacion(BigDecimal value) {
      this.valorModificacion = value;
    }

    /**
     * Gets the value of the moneda property.
     *
     * @return possible object is {@link String }
     */
    public String getMoneda() {
      return moneda;
    }

    /**
     * Sets the value of the moneda property.
     *
     * @param value allowed object is {@link String }
     */
    public void setMoneda(String value) {
      this.moneda = value;
    }

    /**
     * Gets the value of the totalConImpuestos property.
     *
     * @return possible object is {@link TotalConImpuestos }
     */
    public TotalConImpuestos getTotalConImpuestos() {
      return totalConImpuestos;
    }

    /**
     * Sets the value of the totalConImpuestos property.
     *
     * @param value allowed object is {@link TotalConImpuestos }
     */
    public void setTotalConImpuestos(TotalConImpuestos value) {
      this.totalConImpuestos = value;
    }

    /**
     * Gets the value of the motivo property.
     *
     * @return possible object is {@link String }
     */
    public String getMotivo() {
      return motivo;
    }

    /**
     * Sets the value of the motivo property.
     *
     * @param value allowed object is {@link String }
     */
    public void setMotivo(String value) {
      this.motivo = value;
    }
  }
}
