//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.09.25 at 09:10:46 PM ECT
//

package ec.gob.sri.invoice.v210;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Contiene la informacion del destinatario
 *
 * <p>Java class for destino complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="destino"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="motivoTraslado" type="{}motivoTraslado"/&gt;
 *         &lt;element name="docAduaneroUnico" type="{}docAduaneroUnico" minOccurs="0"/&gt;
 *         &lt;element name="codEstabDestino" type="{}establecimiento" minOccurs="0"/&gt;
 *         &lt;element name="ruta" type="{}ruta" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "destino",
    propOrder = {"motivoTraslado", "docAduaneroUnico", "codEstabDestino", "ruta"})
public class Destino {

  @XmlElement(required = true)
  protected String motivoTraslado;

  protected String docAduaneroUnico;
  protected String codEstabDestino;
  protected String ruta;

  /**
   * Gets the value of the motivoTraslado property.
   *
   * @return possible object is {@link String }
   */
  public String getMotivoTraslado() {
    return motivoTraslado;
  }

  /**
   * Sets the value of the motivoTraslado property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMotivoTraslado(String value) {
    this.motivoTraslado = value;
  }

  /**
   * Gets the value of the docAduaneroUnico property.
   *
   * @return possible object is {@link String }
   */
  public String getDocAduaneroUnico() {
    return docAduaneroUnico;
  }

  /**
   * Sets the value of the docAduaneroUnico property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDocAduaneroUnico(String value) {
    this.docAduaneroUnico = value;
  }

  /**
   * Gets the value of the codEstabDestino property.
   *
   * @return possible object is {@link String }
   */
  public String getCodEstabDestino() {
    return codEstabDestino;
  }

  /**
   * Sets the value of the codEstabDestino property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCodEstabDestino(String value) {
    this.codEstabDestino = value;
  }

  /**
   * Gets the value of the ruta property.
   *
   * @return possible object is {@link String }
   */
  public String getRuta() {
    return ruta;
  }

  /**
   * Sets the value of the ruta property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRuta(String value) {
    this.ruta = value;
  }
}
